FROM node

WORKDIR /app

COPY package*.json ./
COPY . .

RUN npm install
RUN npm rebuild bcrypt --build-from-source

COPY src ./src
COPY dist ./dist

ARG BUCKET_ID
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG PROJECT_ID

ENV BUCKET_ID=${BUCKET_ID}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
ENV PROJECT_ID=${PROJECT_ID}


EXPOSE 3000

CMD ["npm", "run", "start:dev"]
