name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Cambia esto si quieres que el workflow se ejecute en otra rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        env:
          GCP_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "$GCP_KEY" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          docker build -t gcr.io/$PROJECT_ID/[NOMBRE_IMAGEN]:[TAG] .
          docker push gcr.io/$PROJECT_ID/[NOMBRE_IMAGEN]:[TAG]
